### ISSUE TITLE
不能用了

### ISSUE THREAD

**Issue by Bthxtly** [admin3999/admin3999.github.io#11]
用了半年，一直可以连，前天（2.2）突然不能用了，连不上

**Comment by SeagullNeo** [comment]
已经失效了，估计是墙发力了，作者也没更新过。。。建议去用这个梯子，有很多梯子工具，抗风险也高不容易挂
链接：[https://github.com/Alvin9999/new-pac/wiki/](url)

**Comment by Neatsuki** [comment]
重新安装试试，我能连，就是速度慢了点

**Comment by admin3999** [comment]
可以哦
